### ISSUE TITLE
Products page UI (for admins)

### ISSUE THREAD

**Issue by kennyphan100** [kennyphan100/SOEN341#107]
**About This Issue**
Story Point(s): 4
Priority: Medium
Risk: Medium

**Describe the Task**
In this products page, all products for a certain are displayed. Each products should be clickable (redirect to another page)
An admin can click on a product and it will redirect them to the "Specific Products Page" (#110)
In this "Product page", the admin can edit the product (change price, change price, change image, etc.)
There should be a button "Add Product"
THIS PAGE SHOULD ONLY BE ACCESSIBLE TO ADMINS

**Comment by karim-tabbara** [comment]
merged.
