### ISSUE TITLE
Populate Products table with data

### ISSUE THREAD

**Issue by kennyphan100** [kennyphan100/SOEN341#33]
**About This Issue**
Story Point(s): 5
Priority: High
Risk: Low

**Task Breakdown**.
Add records (products name, products price, etc) into the database table Products on phpMyAdmin
Make sure the images of each product is located in directory: public > images

This task belongs to the user story https://github.com/kennyphan100/SOEN341/issues/20

**Comment by karim-tabbara** [comment]
completed. all products in database.
