### ISSUE TITLE
Delete unused view files

### ISSUE THREAD

**Issue by kennyphan100** [kennyphan100/SOEN341#81]
**About This Issue**
Story Point(s): 1
Priority: Low
Risk: Low

**Describe the Task**
Delete the unused file "cart.blade.php" located in resources > views > cart
Delete the unused file "welcome.blade.php" located in resources > views
Delete the unused file "dashboard.blade.php" located in resources > views

After deleting these files, make sure to test the whole website to see if it still works

**Exit Criteria**
Clean up directory

**Comment by kevphn** [comment]
Merged.
