### ISSUE TITLE
Create a page that tells the user their order has been confirmed

### ISSUE THREAD

**Issue by sFranchetto** [kennyphan100/SOEN341#84]
**About This Issue**
Story Point(s): 2
Priority: High
Risk: Medium

**Describe the Task**
After the user hits the "checkout" button and the form passes the validation, lead the user to a page that shows their order details and that their order got confirmed.

This task belongs to the user story https://github.com/kennyphan100/SOEN341/issues/96

**Comment by kennyphan100** [comment]
Done and merged!
